import { Form } from "@/components/fields/Form";
import { InputFormField } from "@/components/fields/InputFormField";
import { addTwoFactorApp, removeUnverifiedTwoFactorApp, verifyTwoFactorAuthApp } from "@/dal/auth";
import { SAFormHandler } from "@/lib/SAFormHandler";
import { twoFactorAppName, TwoFactorFormSchema, TwoFactorFormType } from "@/zod/auth";
import { QRCodeCanvas } from 'qrcode.react';
import { useState } from "react";
import { Modal } from "react-bootstrap";
import { UseFormReturn } from "react-hook-form";
import { toast } from "react-toastify";
import { z } from "zod";

export type AppInformation = {
    url: string;
    appId: string;
}
type AddTwoFactorAppModalProps = {
    onClose: () => void;
}
const Step0FormSchema = z.object({
    appName: twoFactorAppName,
})
type Step0FormType = {
    appName: string;
}
export const AddTwoFactorAppModal = ({ onClose }: AddTwoFactorAppModalProps) => {

    const [step, setStep] = useState<0 | 1 | 2>(0);
    const [data, setData] = useState<AppInformation | null>(null);


    const submitStep0 = (data: { appName: string }, form: UseFormReturn<Step0FormType>) => {
        SAFormHandler(
            addTwoFactorApp({ appName: data.appName }),
            form.setError,
            (data) => {
                setData(data);
                setStep(1);
            },
            "An error occurred while adding the app. Please try again."
        );
    }
    const handleCancel = () => {
        if (data) {
            removeUnverifiedTwoFactorApp({
                appId: data.appId
            }).then(() => onClose()).catch(() => {
                toast.error("An error occurred while removing the unverified app. Please check your app list.");
                onClose();
            });
        }
    }
    const submitStep2 = (formData: TwoFactorFormType, form: UseFormReturn<TwoFactorFormType>) => {
        if (!data) return;

        verifyTwoFactorAuthApp({ appId: data.appId, token: formData.token })
            .then((verifyResult) => {
                if (verifyResult.success) {
                    onClose();
                    toast.success("Two-Factor Authentication app added successfully.");
                } else {
                    form.setError("token", { message: verifyResult.error });
                }
            });
    }

    return (
        <Modal show onHide={handleCancel}>
            <Modal.Header closeButton>
                <Modal.Title>Add Two-Factor Authentication App</Modal.Title>
            </Modal.Header>
            {step === 0 && (
                <Form<Step0FormType> onSubmit={submitStep0} zodSchema={Step0FormSchema}>
                    <Modal.Body>
                        <p>Enter a name to Identify the app you would like to add:</p>
                        <InputFormField name="appName" label="App Name" />
                    </Modal.Body>
                    <Modal.Footer>
                        <button type="button" className="btn btn-secondary" onClick={handleCancel}>Cancel</button>
                        <button type="submit" className="btn btn-primary">Next</button>
                    </Modal.Footer>
                </Form>
            )}
            {(step === 1 && data) && (
                <>
                    <Modal.Body>
                        <p>Scan the QR code below with your authentication app (e.g., Google Authenticator, Authy):</p>
                        <QRCodeCanvas value={data.url} />
                    </Modal.Body>
                    <Modal.Footer>
                        <button type="button" className="btn btn-secondary" onClick={handleCancel}>Cancel</button>
                        <button type="button" className="btn btn-primary" onClick={() => setStep(2)}>Next</button>
                    </Modal.Footer>
                </>
            )}
            {(step === 2 && data) && (
                <Form<TwoFactorFormType> onSubmit={submitStep2} zodSchema={TwoFactorFormSchema}>
                    <Modal.Body>
                        <p>Enter the verification token generated by your authentication app to verify the setup:</p>
                        <InputFormField name="token" label="Verification Token" />
                    </Modal.Body>
                    <Modal.Footer>
                        <button type="button" className="btn btn-secondary" onClick={() => setStep(1)}>Back</button>
                        <button type="submit" className="btn btn-primary">Verify</button>
                    </Modal.Footer>
                </Form>
            )}
        </Modal>
    )

}