"use client";

import { TooltipActionButton } from "@/components/Buttons/TooltipIconButton";
import { Form } from "@/components/fields/Form";
import { InputFormField } from "@/components/fields/InputFormField";
import { TextareaFormField } from "@/components/fields/TextareaFormField";
import { resolveDeficiency, updateDeficiency } from "@/dal/inspection/deficiency";
import { swrKeys } from "@/dataFetcher/swrKeys";
import { useScopedI18n } from "@/lib/locales/client";
import { CadetDeficiency, Deficiency } from "@/types/deficiencyTypes";
import { UpdateDeficiencyInput, updateDeficiencySchema } from "@/zod/deficiency";
import { useParams } from "next/navigation";
import { useState } from "react";
import { Col, Row } from "react-bootstrap";
import { toast } from "react-toastify";
import { mutate } from "swr";
import { DeficiencyReadDisplay } from "../_sharedComponents/DeficiencyReadDisplay";

/**
 * Displays a single deficiency row in standalone mode (no active inspection).
 *
 * Toggles between a read-only view (with Edit and Resolve action buttons) and an
 * inline edit form that fully replaces the display content — no duplication.
 *
 * @param deficiency - The deficiency to display, edit, or resolve.
 */
export function DeficiencyStandaloneRow({ deficiency }: { deficiency: Deficiency }) {
    const tCom = useScopedI18n('common');
    const tInspection = useScopedI18n('cadetDetailPage.inspection');
    const [isEditing, setIsEditing] = useState(false);
    const { cadetId } = useParams<{ cadetId: string }>();

    const isDescriptionAutoGenerated =
        !!(deficiency as CadetDeficiency).fk_uniform || !!(deficiency as CadetDeficiency).fk_material;

    const handleSaveEdit = async (data: UpdateDeficiencyInput) => {
        try {
            await updateDeficiency({ id: deficiency.id!, data });
            await mutate(swrKeys.unresolvedDeficienciesByCadet(cadetId));
            setIsEditing(false);
            toast.success(tInspection('message.deficiencyUpdated'));
        } catch {
            toast.error(tCom('error.actions.save'));
        }
    };

    const handleResolve = async () => {
        try {
            await resolveDeficiency(deficiency.id!);
            await mutate(swrKeys.unresolvedDeficienciesByCadet(cadetId));
            toast.success(tInspection('message.deficiencyResolved'));
        } catch {
            toast.error(tCom('error.actions.save'));
        }
    };

    return (
        <Row
            className="p-1 m-0 position-relative border-bottom border-1 py-3"
            data-testid={`div_olddef_${deficiency.id}`}
        >
            {!isEditing ? (
                <>
                    <DeficiencyReadDisplay deficiency={deficiency} />
                    <div className="position-absolute top-0 end-0 p-2 w-auto">
                        <div className="d-flex flex-column mb-2 justify-content-end">
                            <TooltipActionButton
                                variantKey="edit"
                                testId={`btn_edit_${deficiency.id}`}
                                onClick={() => setIsEditing(true)}
                            />
                            <TooltipActionButton
                                variantKey="resolve"
                                testId={`btn_resolve_${deficiency.id}`}
                                onClick={handleResolve}
                            />
                        </div>
                    </div>
                </>
            ) : (
                <Col xs={12}>
                    <Form<UpdateDeficiencyInput>
                        zodSchema={updateDeficiencySchema}
                        onSubmit={handleSaveEdit}
                        defaultValues={{
                            description: deficiency.description,
                            comment: deficiency.comment,
                        }}
                    >
                        {!isDescriptionAutoGenerated ? (
                            <InputFormField<UpdateDeficiencyInput>
                                name="description"
                                label={tCom('description')}
                                maxLength={30}
                                hookFormValidation
                            />
                        ) : (
                            <div className="mb-2">
                                <small className="text-muted fw-bold">{tCom('description')}</small>
                                <p className="mb-0">{deficiency.description}</p>
                            </div>
                        )}
                        <TextareaFormField<UpdateDeficiencyInput>
                            name="comment"
                            label={tCom('comment')}
                            rows={2}
                            maxLength={1000}
                            hookFormValidation
                        />
                        <div className="d-flex gap-2 mt-2">
                            <TooltipActionButton
                                variantKey="save"
                                buttonType="submit"
                                testId={`btn_save_edit_${deficiency.id}`}
                                onClick={() => { }}
                            />
                            <TooltipActionButton
                                variantKey="cancel"
                                testId={`btn_cancel_edit_${deficiency.id}`}
                                onClick={() => setIsEditing(false)}
                            />
                        </div>
                    </Form>
                </Col>
            )}
        </Row>
    );
}
