import { TooltipActionButton } from "@/components/Buttons/TooltipIconButton";
import { Form } from "@/components/fields/Form";
import { InputFormField } from "@/components/fields/InputFormField";
import { TextareaFormField } from "@/components/fields/TextareaFormField";
import { ToggleFormField } from "@/components/fields/ToggleFormField";
import { resolveDeficiency, updateDeficiency } from "@/dal/inspection/deficiency";
import { swrKeys } from "@/dataFetcher/swrKeys";
import dayjs from "@/lib/dayjs";
import { useScopedI18n } from "@/lib/locales/client";
import { CadetDeficiency, Deficiency } from "@/types/deficiencyTypes";
import { CadetInspectionFormSchema, UpdateDeficiencyInput, updateDeficiencySchema } from "@/zod/deficiency";
import { useParams } from "next/navigation";
import { useState } from "react";
import { Col, Row } from "react-bootstrap";
import { useWatch } from "react-hook-form";
import { toast } from "react-toastify";
import { mutate } from "swr";

/** Step-1 checkbox — must be rendered inside a FormProvider for the inspection form. */
function ResolvedCheckbox({ index }: { index: number }) {
    const tDef = useScopedI18n('common.deficiency');
    const resolved = useWatch({ name: `oldDeficiencyList.${index}.resolved` });
    const toggleText = resolved ? tDef('resolved.true') : tDef('resolved.false');

    return (
        <Col xs={12} xl={12} className={`justify-content-center ${resolved ? "text-success" : "text-danger"}`}>
            <ToggleFormField<CadetInspectionFormSchema>

                name={`oldDeficiencyList.${index}.resolved`}
                label=""
                toggleText={toggleText}
                formName="cadetInspectionForm"
            />
        </Col>
    );
}

/**
 * Displays a single unresolved deficiency row.
 *
 * In step 0 without an active inspection, shows inline Edit and Resolve actions.
 * In step 1, shows the resolve toggle switch.
 * In step 2, shows a compact read-only summary.
 *
 * @param inspectionActive - When false (and step === 0), enables standalone edit/resolve actions.
 */
export function OldDeficiencyRow({
    index,
    step,
    deficiency,
    inspectionActive,
}: {
    index: number;
    step: number;
    deficiency: Deficiency;
    inspectionActive?: boolean;
}) {
    const tCom = useScopedI18n('common');
    const tInspection = useScopedI18n('cadetDetailPage.inspection');

    const [showEditForm, setShowEditForm] = useState(false);
    const { cadetId } = useParams<{ cadetId: string }>();

    const isDescriptionAutoGenerated = !!(deficiency as CadetDeficiency).fk_uniform || !!(deficiency as CadetDeficiency).fk_material;

    const handleSaveEdit = async (data: UpdateDeficiencyInput) => {
        try {
            await updateDeficiency({ id: deficiency.id!, data });
            await mutate(swrKeys.unresolvedDeficienciesByCadet(cadetId));
            setShowEditForm(false);
            toast.success(tInspection('message.deficiencyUpdated'));
        } catch {
            toast.error(tCom('error.actions.save'));
        }
    };

    const handleResolve = async () => {
        try {
            await resolveDeficiency(deficiency.id!);
            await mutate(swrKeys.unresolvedDeficienciesByCadet(cadetId));
            toast.success(tInspection('message.deficiencyResolved'));
        } catch {
            toast.error(tCom('error.actions.save'));
        }
    };

    return (
        <Row
            className={`p-1 m-0 position-relative border-bottom border-1 ${(step == 2) ? "py-1" : "py-3"}`}
            key={`oldDefRow-${deficiency.id}`}
            data-testid={`div_olddef_${deficiency.id}`}
        >
            {(step == 1) && <ResolvedCheckbox index={index} />}
            <Col xs={6} sm={4} className="pt-1">
                <Row>
                    <Col className="fs-8 fw-bold fst-italic align-bottom">
                        {tCom('description')}
                    </Col>
                </Row>
                <Row className="align-top">
                    <Col data-testid={`div_description`} className="align-text-top">
                        {deficiency.description}
                    </Col>
                </Row>
            </Col>
            <Col xs={6} sm={4} className="pt-1">
                <Row>
                    <Col className="fs-8 fw-bold fst-italic">
                        {tCom('type')}
                    </Col>
                </Row>
                <Row>
                    <Col data-testid={`div_type`}>
                        {deficiency.typeName}
                    </Col>
                </Row>
            </Col>
            {(step < 2) &&
                <Col xs={6} sm={4} className="pt-1">
                    <Row>
                        <Col className="fs-8 fw-bold fst-italic">
                            {tCom('dates.created')}
                        </Col>
                    </Row>
                    <Row>
                        <Col data-testid={`div_created`}>
                            {dayjs(deficiency.dateCreated).format('DD.MM.YYYY')}
                        </Col>
                    </Row>
                </Col>
            }
            {(step < 2) &&
                <Col xs={"12"} className="pt-2">
                    <Row>
                        <Col className="fs-8 fw-bold fst-italic">
                            {tCom('comment')}
                        </Col>
                    </Row>
                    <Row>
                        <Col data-testid={`div_comment`}>
                            {deficiency.comment}
                        </Col>
                    </Row>
                </Col>
            }
            {!inspectionActive && (
                <div className="position-absolute top-0 end-0 p-2 w-auto">
                    <div className="d-flex flex-column mb-2 justify-content-end">
                        <TooltipActionButton
                            variantKey="edit"
                            testId={`btn_edit_${deficiency.id}`}
                            onClick={() => setShowEditForm((v) => !v)}
                        />
                        <TooltipActionButton
                            variantKey="resolve"
                            testId={`btn_resolve_${deficiency.id}`}
                            onClick={handleResolve}
                        />
                    </div>
                </div>
            )}
            {(step === 0 && !inspectionActive) && (
                <Col xs={12} className="pt-2">
                    {showEditForm && (
                        <Form<UpdateDeficiencyInput>
                            zodSchema={updateDeficiencySchema}
                            onSubmit={handleSaveEdit}
                            defaultValues={{
                                description: deficiency.description,
                                comment: deficiency.comment,
                            }}
                        >
                            <div className="border rounded p-2 bg-light">
                                {!isDescriptionAutoGenerated && (
                                    <InputFormField<UpdateDeficiencyInput>
                                        name="description"
                                        label={tCom('description')}
                                        maxLength={30}
                                        hookFormValidation
                                    />
                                )}
                                {isDescriptionAutoGenerated && (
                                    <div className="mb-2">
                                        <small className="text-muted fw-bold">{tCom('description')}</small>
                                        <p className="mb-0">{deficiency.description}</p>
                                    </div>
                                )}
                                <TextareaFormField<UpdateDeficiencyInput>
                                    name="comment"
                                    label={tCom('comment')}
                                    rows={2}
                                    maxLength={1000}
                                    hookFormValidation
                                />
                                <div className="d-flex gap-2 mt-2">
                                    <TooltipActionButton
                                        variantKey="save"
                                        buttonType="submit"
                                        testId={`btn_save_edit_${deficiency.id}`}
                                        onClick={() => { }}
                                    />
                                    <TooltipActionButton
                                        variantKey="cancel"
                                        testId={`btn_cancel_edit_${deficiency.id}`}
                                        onClick={() => setShowEditForm(false)}
                                    />
                                </div>
                            </div>
                        </Form>
                    )}
                </Col>
            )}
        </Row>
    );
}
