# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Validate MR
on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI
    env:
      DATABASE_URL: ${{ vars.DATABASE_URL }}
      IRON_SESSION_KEY: ${{ vars.IRON_SESSION_KEY }}
      IRON_SESSION_COOKIE_NAME: ${{ vars.IRON_SESSION_COOKIE_NAME }}
      REFRESH_TOKEN_KEY: ${{ vars.REFRESH_TOKEN_KEY }}
      CI: true
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ vars.DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ vars.DATABASE_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: 22.14.0
        cache: 'npm'
    - name: install dependencies
      run: npm i
    - name: setup database
      run: npx prisma migrate deploy && npx prisma db seed
    - name: run jest tests
      run: npm run test:jest
    - name: build the application
      run: npm run build 
    - name: install Playwright runners
      run: npx playwright install
    - name: run e2e tests
      run: npm run test:e2e
    - uses: actions/upload-artifact@v4
      if: ${{ failure() && steps.e2e.outcome == 'failure' }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
